---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  #hosts: all
  become: yes
  become_method: sudo

  #roles:
  #  - common

- name: configure and deploy the webservers and application code
  hosts: /managed/group/webservers
  become: yes
  become_method: sudo
#  ignore_errors: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: /managed/group/dbservers
  become: yes
  become_method: sudo

  roles:
    - db
