---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all nodes
  hosts: all
  become: yes
 # roles:
 #   - common

- name: configure and deploy the webservers and application code
  hosts: all
  become: yes
#  ignore_errors: yes

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: all
  become: yes

  roles:
    - db
